spring.application.name=lms
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/lms
spring.datasource.username=lms
spring.datasource.password=lms
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# JWT
jwt.secret=Q2hhbmdlTWVUb0FTdHJvbmdSYW5kb21TZWNyZXRLZXlGb3JQcm9kdWN0aW9uVXNlT25seVBsZWFzZQ==
jwt.expiration-ms=604800000

# File storage (TICKET-BE-12)
storage.path=./uploads
app.base-url=http://localhost:8080
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# SpringDoc
springdoc.default-flat-param-object=true

# Actuator (TICKET-BE-15)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Logging (TICKET-BE-15)
logging.level.root=INFO
logging.level.com.example.lms=INFO
